// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-qZGkYyQefbASxGjY1G9RMoRjG9PMQiE',
    appId: '1:376372160106:android:4eccd20e1f038d07524c13',
    messagingSenderId: '376372160106',
    projectId: 'we-chat-148dc',
    storageBucket: 'we-chat-148dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRJ0GyYm5xJ0ehDkPwjmE8jZ95xWhy7es',
    appId: '1:376372160106:ios:a4062ca718dcd50b524c13',
    messagingSenderId: '376372160106',
    projectId: 'we-chat-148dc',
    storageBucket: 'we-chat-148dc.appspot.com',
    androidClientId: '376372160106-3nrtadv2n5341q4uiuts76l289676u4o.apps.googleusercontent.com',
    iosClientId: '376372160106-hcm2p7pbftg4l5v121ne36aeqh2mrig1.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymessages',
  );
}
